package dagworker

import "unicode/utf8"

// Scope is a namespace: the unit of isolation, configuration, completion,
// retention, and key prefixing. Scopes are created implicitly on first write.
//
// An edge never crosses a scope boundary. That restriction is what keeps cycle
// checking, completion detection, and garbage collection provably scope-local,
// which in turn is what makes every operation's cost independent of the total
// number of nodes in the backend.
type Scope string

// NodeID identifies a node within a scope. It is supplied by the caller, never
// generated by the library, so that a caller retrying after a timeout can
// express "the same node" rather than accidentally creating a second one.
type NodeID string

// Seq is a per-node monotonic sequence number, assigned atomically with every
// state write to that node. It orders events for one node and detects stale
// reads: a snapshot with a lower Seq than one you already saw is older.
//
// There is no cross-node ordering guarantee from Seq and none should be
// inferred. Two nodes' sequences are unrelated numbers.
type Seq uint64

// Cursor is a scope-wide monotonic position in the scope's event log. It is
// what a subscription resumes from, because a per-node sequence cannot order a
// stream that spans nodes.
//
// The split mirrors etcd, which likewise needs both a per-key ModRevision for
// staleness and a store-wide Revision for watch resumption: one number cannot
// do both jobs. The counter is per scope, not global, so scopes never contend
// with each other for it — within a scope, writes are already serialized by the
// atomicity the storage port requires, so the counter costs nothing extra.
type Cursor uint64

// Limits on identifier sizes. These are checked on every write path, cheaply,
// so an oversized key can never reach a backend and fail there with a less
// intelligible error.
const (
	// MaxScopeLen is the longest permitted scope name, in bytes.
	MaxScopeLen = 255
	// MaxNodeIDLen is the longest permitted node ID, in bytes.
	MaxNodeIDLen = 255
	// MaxKindLen is the longest permitted kind, in bytes.
	MaxKindLen = 64
	// MaxLabelKeyLen is the longest permitted label key, in bytes.
	MaxLabelKeyLen = 64
	// MaxLabelValueLen is the longest permitted label value, in bytes.
	MaxLabelValueLen = 256
	// MaxLabels is the most labels a single node may carry.
	MaxLabels = 32
)

func (s Scope) validate() error {
	switch {
	case len(s) == 0:
		return invalidArg("scope", "must not be empty")
	case len(s) > MaxScopeLen:
		return invalidArg("scope", "is %d bytes, limit is %d", len(s), MaxScopeLen)
	case !utf8.ValidString(string(s)):
		return invalidArg("scope", "is not valid UTF-8")
	default:
		return nil
	}
}

func (n NodeID) validate() error {
	switch {
	case len(n) == 0:
		return invalidArg("node id", "must not be empty")
	case len(n) > MaxNodeIDLen:
		return invalidArg("node id", "is %d bytes, limit is %d", len(n), MaxNodeIDLen)
	case !utf8.ValidString(string(n)):
		return invalidArg("node id", "is not valid UTF-8")
	default:
		return nil
	}
}

func validateKind(kind string) error {
	switch {
	case len(kind) > MaxKindLen:
		return invalidArg("kind", "is %d bytes, limit is %d", len(kind), MaxKindLen)
	case !utf8.ValidString(kind):
		return invalidArg("kind", "is not valid UTF-8")
	default:
		return nil
	}
}

func validateLabels(labels map[string]string) error {
	if len(labels) > MaxLabels {
		return invalidArg("labels", "has %d entries, limit is %d", len(labels), MaxLabels)
	}
	for k, v := range labels {
		switch {
		case len(k) == 0:
			return invalidArg("label key", "must not be empty")
		case len(k) > MaxLabelKeyLen:
			return invalidArg("label key", "%q is %d bytes, limit is %d", k, len(k), MaxLabelKeyLen)
		case len(v) > MaxLabelValueLen:
			return invalidArg("label value", "for %q is %d bytes, limit is %d", k, len(v), MaxLabelValueLen)
		case !utf8.ValidString(k) || !utf8.ValidString(v):
			return invalidArg("label", "%q is not valid UTF-8", k)
		}
	}
	return nil
}
