import { defineCollection } from 'astro:content'
import { docsLoader } from '@astrojs/starlight/loaders'
import { docsSchema } from '@astrojs/starlight/schema'

// src/content/docs is generated by scripts/ingest.mjs from the repository's
// own Markdown. It is not committed; see that script for why the sources are
// adapted rather than moved.
export const collections = {
  docs: defineCollection({ loader: docsLoader(), schema: docsSchema() }),
}
