-- Schema for the PostgreSQL dagworker backend.
--
-- Every enum-shaped column (status, reason, phase, trigger_rule, event kind)
-- stores the exact numeric value of the corresponding Go type in package
-- dagworker, rather than a Postgres ENUM or a text vocabulary of its own.
-- Duplicating the vocabulary here would be a second source of truth that the
-- Go side and the SQL side could drift out of sync with; storing the raw
-- integer means there is exactly one place the mapping is defined.
--
-- clock_timestamp() is used for every timestamp this schema writes. The
-- transaction-start-time functions are deliberately never called here: they
-- would freeze at the wrong instant for a deadline (ADR-0008). CI greps every
-- .sql file under this package for that banned call and must never find one.

CREATE SCHEMA IF NOT EXISTS dagw;

-- scopes is the per-scope policy, seal flag, and the O(1) counters
-- ScopeStats reads. Every mutating operation below touches this row once (to
-- move a node between phase buckets, or to advance the sealed/complete
-- flags), which makes it the one deliberately serializing point per scope —
-- an accepted tradeoff for exact, scan-free stats. Cursor, topological rank
-- and ready-set FIFO order are deliberately NOT columns here: they are
-- generated by identity columns and a sequence on the tables that need them
-- (below), specifically so that assigning one never contends on this row.
CREATE TABLE IF NOT EXISTS dagw.scopes (
    scope                     text PRIMARY KEY,
    sealed                    boolean     NOT NULL DEFAULT false,

    -- ScopeConfig, field for field. A duration's zero means "inherit the
    -- library's fallback" (ScopeConfig.Resolved) except where noted; storing
    -- the raw stored value (not the resolved one) is what makes
    -- T-SCOPE-CONFIG-ROUNDTRIP an exact round trip.
    default_lease_timeout_ns bigint      NOT NULL DEFAULT 0,
    min_lease_timeout_ns     bigint      NOT NULL DEFAULT 0,
    max_lease_timeout_ns     bigint      NOT NULL DEFAULT 0,
    max_attempts             integer     NOT NULL DEFAULT 0,
    retry_base_delay_ns      bigint      NOT NULL DEFAULT 0,
    retry_max_delay_ns       bigint      NOT NULL DEFAULT 0,
    terminal_retention_ns    bigint      NOT NULL DEFAULT 0,
    max_subscriber_lag_ns    bigint      NOT NULL DEFAULT 0,
    max_in_flight            integer     NOT NULL DEFAULT 0,
    payload_cap              integer     NOT NULL DEFAULT 0,
    max_batch_size           integer     NOT NULL DEFAULT 0,
    sweep_batch_size         integer     NOT NULL DEFAULT 0,
    sweep_interval_ns        bigint      NOT NULL DEFAULT 0,
    partition_count          integer     NOT NULL DEFAULT 0,

    -- Incremental counters. Never derived by scanning dagw.nodes.
    stat_total               bigint      NOT NULL DEFAULT 0,
    stat_blocked             bigint      NOT NULL DEFAULT 0,
    stat_scheduled           bigint      NOT NULL DEFAULT 0,
    stat_ready               bigint      NOT NULL DEFAULT 0,
    stat_in_progress         bigint      NOT NULL DEFAULT 0,
    stat_succeeded           bigint      NOT NULL DEFAULT 0,
    stat_failed              bigint      NOT NULL DEFAULT 0,

    created_at                timestamptz NOT NULL DEFAULT clock_timestamp()
);

-- One global sequence for ready-set FIFO order, shared across every scope.
-- Sharing it is safe because a claim never compares nodes across scopes, and
-- deliberate: a Postgres sequence hands out values without taking a row lock
-- or blocking on a concurrent transaction, so it cannot become the kind of
-- serializing bottleneck a per-scope counter row would be on the claim path.
CREATE SEQUENCE IF NOT EXISTS dagw.fifo_seq;

-- nodes is the wide row. `id` is the surrogate key every lock-ordering rule
-- in this backend sorts on ("ascending node id", per ADR-0038); `rank` is the
-- Pearce-Kelly topological order number and is a SEPARATE identity so that
-- edge insertion can renumber it independently of row creation order.
-- fillfactor and per-table autovacuum settings are shipped here, in the
-- migration, rather than as tuning advice: a queue-shaped table churns far
-- faster than autovacuum's stock thresholds assume (dossier 04 §8, §9).
CREATE TABLE IF NOT EXISTS dagw.nodes (
    id                  bigint      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    -- BY DEFAULT, not ALWAYS: a fresh node gets an auto-assigned rank exactly
    -- like ALWAYS would give it, but Pearce-Kelly's reorder step (topo.go)
    -- must be able to overwrite an existing node's rank with a reused value
    -- from its affected region, which GENERATED ALWAYS categorically forbids
    -- even via UPDATE.
    rank                bigint      GENERATED BY DEFAULT AS IDENTITY,
    scope               text        NOT NULL,
    node_id             text        NOT NULL,
    kind                text        NOT NULL DEFAULT '',

    status              smallint    NOT NULL CHECK (status BETWEEN 0 AND 3),
    reason              smallint    NOT NULL DEFAULT 0 CHECK (reason BETWEEN 0 AND 6),
    message             text        NOT NULL DEFAULT '',
    phase               smallint    NOT NULL CHECK (phase BETWEEN 0 AND 4),

    attempt             integer     NOT NULL DEFAULT 0,
    epoch               bigint      NOT NULL DEFAULT 0,
    priority            smallint    NOT NULL DEFAULT 0,
    trigger_rule        smallint    NOT NULL DEFAULT 0 CHECK (trigger_rule BETWEEN 0 AND 4),

    retry_max_attempts  integer     NOT NULL DEFAULT 0,
    retry_base_delay_ns bigint      NOT NULL DEFAULT 0,
    retry_max_delay_ns  bigint      NOT NULL DEFAULT 0,

    payload             bytea,
    result              bytea,
    labels              jsonb,
    worker              text        NOT NULL DEFAULT '',

    seq                 bigint      NOT NULL DEFAULT 0,
    fifo                bigint      NOT NULL DEFAULT 0,

    -- The incremental predecessor tally a trigger rule is evaluated against
    -- (dagworker.DepCounts). Maintained by the same statement that resolves a
    -- predecessor, never recomputed by scanning edges.
    deps_unsatisfied    integer     NOT NULL DEFAULT 0,
    deps_succeeded      integer     NOT NULL DEFAULT 0,
    deps_skipped        integer     NOT NULL DEFAULT 0,
    deps_failed         integer     NOT NULL DEFAULT 0,

    deadline            timestamptz,
    ready_at            timestamptz,

    created_at          timestamptz NOT NULL,
    updated_at          timestamptz NOT NULL,

    UNIQUE (scope, node_id)
)
WITH (
    fillfactor = 80,
    autovacuum_vacuum_scale_factor = 0.02,
    autovacuum_vacuum_cost_delay = 2,
    autovacuum_vacuum_insert_scale_factor = 0.02
);

-- The ONLY index the claim query touches. Partial on phase=ready, so it stays
-- tiny regardless of how many terminal rows the scope accumulates (dossier
-- 04 §6) — the literal predicate must match the claim query's literal WHERE
-- clause verbatim or the planner will not recognise it applies.
CREATE INDEX IF NOT EXISTS nodes_ready_idx
    ON dagw.nodes (scope, priority DESC, fifo)
    WHERE phase = 2;

-- Drives the sweeper: bounded by concurrently in-flight nodes, never by
-- total scope size (dossier 04 §7).
CREATE INDEX IF NOT EXISTS nodes_deadline_idx
    ON dagw.nodes (scope, deadline)
    WHERE phase = 3;

-- Drives retry-backoff promotion the same way: partial and deadline-shaped.
CREATE INDEX IF NOT EXISTS nodes_scheduled_idx
    ON dagw.nodes (scope, ready_at)
    WHERE phase = 1;

-- edges. satisfied is the per-edge flag ADR-0005 requires: completion marks
-- exactly the edges it resolves, which is what makes the fan-out idempotent
-- under a repeated or duplicated apply.
CREATE TABLE IF NOT EXISTS dagw.edges (
    scope       text    NOT NULL,
    from_id     bigint  NOT NULL REFERENCES dagw.nodes (id) ON DELETE CASCADE,
    to_id       bigint  NOT NULL REFERENCES dagw.nodes (id) ON DELETE CASCADE,
    satisfied   boolean NOT NULL DEFAULT false,
    PRIMARY KEY (scope, from_id, to_id)
);

-- Reverse lookup: "who depends on this node" (predecessor tallying, Inspect's
-- Waiting list). The primary key already serves the forward direction
-- ("what does this node depend on").
CREATE INDEX IF NOT EXISTS edges_to_idx ON dagw.edges (scope, to_id, from_id);

-- events is the durable, replayable log backing Watch. cursor is a global
-- identity for the same non-contending reason fifo_seq is global: a scope's
-- own cursor sequence is strictly increasing (all that Watch's resume
-- contract requires) even though the numbers are not contiguous within one
-- scope. pg_notify (emitted by the application, not a trigger, so it can
-- carry a payload derived from the whole batch of effects one write
-- produced) is a latency hint layered on top of this table, never a
-- replacement for it (dossier 04 §3, §4).
CREATE TABLE IF NOT EXISTS dagw.events (
    scope       text        NOT NULL,
    cursor      bigint      GENERATED ALWAYS AS IDENTITY,
    node_id     text        NOT NULL,
    kind        smallint    NOT NULL CHECK (kind BETWEEN 0 AND 2),
    seq         bigint      NOT NULL,
    from_status smallint    NOT NULL CHECK (from_status BETWEEN 0 AND 3),
    to_status   smallint    NOT NULL CHECK (to_status BETWEEN 0 AND 3),
    reason      smallint    NOT NULL DEFAULT 0,
    message     text        NOT NULL DEFAULT '',
    attempt     integer     NOT NULL DEFAULT 0,
    node_kind   text        NOT NULL DEFAULT '',
    at          timestamptz NOT NULL,
    PRIMARY KEY (scope, cursor)
);
